# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Yasir ul Hadi
description: "Hi, I’m Yasir, and I’m a Data Scientist with 5+ years of experience building AI and ML systems that scale and create measurable business impact. Focused on LLMs, MLOps, and predictive analytics to build production ready AI applications. You can explore my GitHub and LinkedIn profiles below, or download my Résumé to learn more about my work."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "New Delhi"
resume_url: /docs/Yasir ul Hadi_Resume.pdf
avatar_image: /img/Profile_picture.JPG

#-------------------------------
# Contact links
linkedln: "https://linkedln.com/yasirhadi" # Add your linkedln handle
github: "https://github.com/yasirulhadi"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


